package de.bened.wikixtractor;

import org.neo4j.graphdb.Node;

/**
 * <h1>Page</h1>
 * Creates Page objects
 *
 * @author xuiqzy
 * @since 07.11.2016
 */
class Page {

    private final Node pageNode;

    Page(int pageID, int namespaceID, String title, String htmlContent) {
        this.pageNode = DatabaseManager.createPageNode(namespaceID, pageID, title, htmlContent);
    }


    /**
     * @return id of the page
     */
    int getPageID() {
        return (int) DatabaseManager.getPropertyFromNode(this.pageNode, "PageID");
    }

    /**
     * @return namespace of the page: 0 for an article, 14 for a category page
     */
    int getNamespaceID() {
        return (int) DatabaseManager.getPropertyFromNode(this.pageNode, "NamespaceID");
    }

    /**
     * @return title of the page
     */
    String getTitle() {
        return (String) DatabaseManager.getPropertyFromNode(this.pageNode, "Title");
    }

    /**
     * generated by Intellij Idea
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Page page = (Page) o;

        if (getPageID() != page.getPageID()) return false;
        if (getNamespaceID() != page.getNamespaceID()) return false;
        return getTitle() != null ? getTitle().equals(page.getTitle()) : page.getTitle() == null;
    }

    /**
     * generated by Intellij Idea
     */
    @Override
    public int hashCode() {
        int result = getPageID();
        result = 31 * result + getNamespaceID();
        result = 31 * result + (getTitle() != null ? getTitle().hashCode() : 0);
        return result;
    }
}
