package de.bened.wikixtractor;

import java.util.Set;

/**
 * @author xuiqzy
 */
class Page {
    /**
     * id of the page
     */
    private final int pageID;
    /**
     * id of the namespace: 0 for an article, 14 for a category page
     */
    private final int namespaceID;
    /**
     * title of the page
     */
    private final String title;
    /**
     * titles of the categories the page belongs to
     */
    private final Set<String> categories;

    /**
     * @param pageID id of the page
     * @param namespaceID namespace of the page: 0 for article, 14 for a category page
     * @param title title of page
     * @param categories titles of categories the page belongs to
     */
    Page(int pageID, int namespaceID, String title, Set<String> categories) {
        this.pageID = pageID;
        this.namespaceID = namespaceID;
        this.title = title;
        this.categories = categories;
    }


    /**
     * @return id of the page
     */
    int getPageID() {
        return pageID;
    }

    /**
     * @return namespace of the page: 0 for an article, 14 for a category page
     */
    int getNamespaceID() {
        return namespaceID;
    }

    /**
     * @return title of the page
     */
    String getTitle() {
        return title;
    }

    /**
     * @return titles of the categories the page belongs to
     */
    Set<String> getCategories() {
        return categories;
    }


    /**
     * generated by Intellij Idea, simplified by me (xuiqzy) with the inspection hints from Intellij Idea
     *
     * @param o Object to compare to
     * @return true if objects have the same attributes, false otherwise
     */
    //
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Page page = (Page) o;

        return pageID == page.pageID && namespaceID == page.namespaceID &&
                (title != null ? title.equals(page.title) : page.title == null) &&
                (categories != null ? categories.equals(page.categories) : page.categories == null);
    }

    /**
     * generated by Intellij Idea
     *
     * @return unique hash identified by the values of all attributes
     */
    @Override
    public int hashCode() {
        int result = pageID;
        result = 31 * result + namespaceID;
        result = 31 * result + (title != null ? title.hashCode() : 0);
        result = 31 * result + (categories != null ? categories.hashCode() : 0);
        return result;
    }
}
