package de.bened.wikixtractor;

import org.neo4j.graphdb.Node;

import java.util.Set;

/**
 * <h1>Page</h1>
 * Creates Page objects
 *
 * @author xuiqzy
 * @since 07.11.2016
 */
class Page {

    private final Node pageNode;
    /**
     * id of the page
     */
    private final int pageID;
    /**
     * id of the namespace: 0 for an article, 14 for a category page
     */
    private final int namespaceID;
    /**
     * title of the page
     */
    private final String title;

    /**
     * @param pageID id of the page
     * @param namespaceID namespace of the page: 0 for article, 14 for a category page
     * @param title title of page
     * @param htmlContent html content of the page
     */
    Page(int pageID, int namespaceID, String title, String htmlContent) {
        this.pageNode = DatabaseManager.createPageNote(namespaceID, pageID, title, htmlContent);
        this.pageID = pageID;
        this.namespaceID = namespaceID;
        this.title = title;
    }


    /**
     * @return id of the page
     */
    int getPageID() {
        return pageID;
    }

    /**
     * @return namespace of the page: 0 for an article, 14 for a category page
     */
    int getNamespaceID() {
        return namespaceID;
    }

    /**
     * @return title of the page
     */
    String getTitle() {
        return title;
    }

    /**
     * generated by Intellij Idea
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Page page = (Page) o;

        if (getPageID() != page.getPageID()) return false;
        if (getNamespaceID() != page.getNamespaceID()) return false;
        return getTitle() != null ? getTitle().equals(page.getTitle()) : page.getTitle() == null;
    }

    /**
     * generated by Intellij Idea
     */
    @Override
    public int hashCode() {
        int result = getPageID();
        result = 31 * result + getNamespaceID();
        result = 31 * result + (getTitle() != null ? getTitle().hashCode() : 0);
        return result;
    }
}
